### ISSUE TITLE
Contradicting data in rd.rex

### ISSUE THREAD

**Issue by Elmue** [abend0c1/hidrdd#1]
k.0UNIT.0000E121 = 'Energy in joules [0.1 μJ units],-7 J'
k.0UNIT.0000E121 = 'Moment of force in newton metres [0.1 μN m units],-7 N m'
k.0UNIT.0000E121 = 'Surface tension in newton per metre [1 g/s² units],-3 kg/s²'
three times the same value for 3 different things ?

k.0UNIT.010000E1 = 'Luminance [1 cd/cm² units],4 cd/m²'
is assigned twice

**Comment by abend0c1** [comment]
Nice pick up...the Surface tension unit was incorrect - it should be 0000E101, and I accidentally duplicated Luminance.

As for the "Moment of force" and "Energy" units - they actually have the same underlying units - so I will keep Energe and discard the "Moment of force" as it is less intuitive. There are quite a few SI derived units that have the same underlying units - so when they are decoded there is no way to determine which one the original author intended, so I just decode one of them.

**Comment by Elmue** [comment]
I have never seen such a STUPID thing as the USB Unit system. It is the biggest design error. Why did they not use a simple enumeration for the Units? For example: 
01 = meter
02 = inch
03 = radians
04 = angular velocity
05 = Pascal
06 = Newton
07 = Ampere
08 = Volt
etc...
The nonsense with SI and english systems would not be necessary anymore.
With an additional exponent they could have easily added milli, micro, kilo, Mega, Giga etc...
It could be so simple. Instead of using the base units (meter) they use centimeter! What morons invented this?
The current stupid unit system does not allow to distingush between Hertz and Bequerel which both have the same unit. I have never seen such a stupid thing as the highly complicated unit for voltage (Volt = kg·m2/(s3·A)) which even measures in units of 0,1µV. And they even need 4 Bytes for that unit.
