### ISSUE TITLE
Missing Pages

### ISSUE THREAD

**Issue by Elmue** [abend0c1/hidrdd#2]
Please add the following two usage pages to the *.conf files:

0080.conf:

PAGE 80 Monitor
01 Monitor Control
02 EDID Information
03 VDIF Information
04 VESA Version

// -------------------------------------------------------

0082.conf:

PAGE 82 VESA Virtual Control
01 Degauss
10 Brightness
12 Contrast
16 Red Video Gain
18 Green Video Gain
1A Blue Video Gain
1C Focus
20 Horizontal Position
22 Horizontal Size
24 Horizontal Pincushion
26 Horizontal Pincushion Balance
28 Horizontal Misconvergence
2A Horizontal Linearity
2C Horizontal Linearity Balance
30 Vertical Position
32 Vertical Size
34 Vertical Pincushion
36 Vertical Pincushion Balance
38 Vertical Misconvergence
3A Vertical Linearity
3C Vertical Linearity Balance
40 Parallelogram Distortion
42 Trapezoidal Distortion
44 Tilt
46 Top Corner Distortion Control
48 Top Corner Distortion Balance
4A Bottom Corner Distortion Control
4C Bottom Corner Distortion Balance
56 Horizontal Moiré
58 Vertical Moiré
5E Input Level Select
60 Input Source Select
6C Red Video Black Level
6E Green Video Black Level
70 Blue Video Black Level
A2 Auto Size Center
A4 Polarity Horizontal Synchronization
A6 Polarity Vertical Synchronization
A8 Synchronization Type
AA Screen Orientation
AC Horizontal Frequency
AE Vertical Frequency
B0 Settings
CA On Screen Display
D4 Stereo Mode

**Comment by abend0c1** [comment]
Hi Elmue, 

I omitted usage page 80 because the Monitor spec was old and appeared to be created to support what I consider to be "dead" technology: CRT displays. However, it's no problem to add them if people find it handy.

Cheers,
Andrew.

**Comment by Elmue** [comment]
Hello Andrew
Your library is the best and the most accurate that I found in internet.
I think you should just offer the information and the people who download your files can then decide if it is usefull for them or not. Maybe in you country CRT monitors are not used anymore. But I'am sure that in Africa or in India there are still lots of CRT monitos in use today. So if you add these two files this Github project will be the best source for HID data because everything else that I found in internet was incomplete or even containing wrong data.

**Comment by abend0c1** [comment]
Fixed #2
