### ISSUE TITLE
Wrong calculations in rd.rex

### ISSUE THREAD

**Issue by Elmue** [abend0c1/hidrdd#3]
I checked all your units that can be found here:
https://www.unc.edu/~rowlett/units/siderive.html

As far as I see they are correct with 2 exceptions:
k.0UNIT.0000F002 = 'Angular velocity [1 rad/s units],0 rad/s'
k.0UNIT.0000E002 = 'Angular acceleration [1 rad/s² units],0 rad/s²'
are wrong.

Correct would be:
k.0UNIT.0000F012 = 'Angular velocity [1 rad/s units],0 rad/s'
k.0UNIT.0000E012 = 'Angular acceleration [1 rad/s² units],0 rad/s²'

**Comment by abend0c1** [comment]
Hi Elmue,

Angular velocity/acceleration do not depend on length, so the units are correct as they stand. Angular velocity is measured in radians per second. A radian is dimensionless, so the underlying unit is simply 'per second'. You can think of angular velocity in terms of either radians per second or revolutions per minute (RPM) - they are both independent of length or distance.

Thanks for you feedback - it's prompted me to revisit this area again. :)
Cheers,
Andrew.

**Comment by abend0c1** [comment]
Oops. You're right. I've just reread the doco and nibble 2 is not used as Length when the system is SI or English Rotation.

Thanks for pointing out this error :)
