### ISSUE TITLE
C structures padding is not considered

### ISSUE THREAD

**Issue by jm4R** [abend0c1/hidrdd#6]
Th C file output may be missleading, for example UPS device:

```
typedef struct
{
  uint8_t  reportId;                                 // Report ID = 0x15 (21)
                                                     // Collection: CA:UPS CP:Output
  int16_t  POW_UPSOutputDelayBeforeShutdown;         // Usage 0x00840057: Delay Before Shutdown, Value = -1 to 32767, Physical = ((Value + 1) x 60 - 60) in s
} featureReport15_t;
```

This struct (in most common platforms) is of 4 bytes size (1 byte report ID + 1 byte padding + 2 bytes value). It can't be used to serialize the report, because report's doesn't expect any padding. One can enable compiler-specific structure packing mode, but at least warning in documentation should be noted.

**Comment by abend0c1** [comment]
You are quite right. I've added a #pragma that should work for the most people - and added a note to the README. Thanks for pointing this out.
